version: "3.7"

services:
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: web_flask
    container_name: flaskkollectordev
    restart: always
    ports:
      - "5000:5000"
    # depends_on:
    #   - mongodb
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - DATABASE_URL=mongodb://username:passsword@localhost:27017/development?authSource=admin
    # env_file:
    #     - .env
    volumes:
      - .:/usr/app
      command: sh -c "flask run --host=0.0.0.0 --port=5000"

networks:
  default:
    external:
      name: kollector-network
