version: "3.7"

services:
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: web_flask
    container_name: flaskkollector
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://username:passsword@localhost:27017/development?authSource=admin
    # env_file:
    #     - .env
networks:
  default:
    external:
      name: kollector-network
