[default]
DEBUG = false
FLASK_ADMIN_NAME = "Kollector Admin"
FLASK_ADMIN_TEMPLATE_MODE = "bootstrap3"
FLASK_ADMIN_SWATCH = 'cerulean'
# SQLALCHEMY_DATABASE_URI = 'mongodb:///development.db'
TITLE = "Kollector"
SECRET_KEY = "68E543563EB398C48F7146FCCC23B"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
EXTENSIONS = [
    "Kollector.src.extensions.utils.appearance:init_app",
    "Kollector.src.extensions.utils.database:init_app",
    "Kollector.src.extensions.utils.auth:init_app",
    "Kollector.src.extensions.utils.admin:init_app",
    "Kollector.src.extensions.utils.commands:init_app",
    "Kollector.src.domain.api.api_v1.endpoints.webui:init_app",
    "Kollector.src.domain.api.api_v1.endpoints.restapi:init_app",
    "Kollector.src.domain.api.api_v1.endpoints.routes:init_app",
]


[development]
EXTENSIONS = [
    "flask_debugtoolbar:DebugToolbarExtension",
    "dynaconf_merge_unique"  # to reuse extensions list from [default]
]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
DEBUG_TOOLBAR_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PANELS = [
    "flask_debugtoolbar.panels.versions.VersionDebugPanel",
    "flask_debugtoolbar.panels.sqlalchemy.SQLAlchemyDebugPanel",
    "flask_debugtoolbar.panels.timer.TimerDebugPanel",
    "flask_debugtoolbar.panels.headers.HeaderDebugPanel",
    "flask_debugtoolbar.panels.request_vars.RequestVarsDebugPanel",
    "flask_debugtoolbar.panels.template.TemplateDebugPanel",
    "flask_debugtoolbar.panels.route_list.RouteListDebugPanel",
    "flask_debugtoolbar.panels.logger.LoggingPanel",
    "flask_debugtoolbar.panels.profiler.ProfilerDebugPanel",
    "flask_debugtoolbar.panels.config_vars.ConfigVarsDebugPanel"
]

[testing]
# MONGODB_DATABASE_URI = 'mongodb:///testing.db'

[production]
# MONGODB_DATABASE_URI = 'mongodb:///production.db'

[staging]
# MONGODB_DATABASE_URI = 'mongodb:///production.db'
# EXEMPLO (APAGAR DEPOIS) MONGODB_URL=mongodb://username:password@localhost:27017/development?authSource=admin
